imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: doctrine_extensions.yml }
  - { resource: "@ECommerceBundle/Resources/config/services.yml" }

framework:
  #esi:             ~
  translator: { fallback: es }
  #translator:      ~
  secret: "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  templating:
    engines: ["twig"]
    #assets_version: SomeVersionScheme
  default_locale: es
  trusted_hosts: ~
  trusted_proxies: ~
  session:
    # handler_id set to null will use default session handler from php.ini
    handler_id: ~
  fragments: ~
  http_method_override: true

services:
  gedmo.listener.softdeleteable:
    class: Gedmo\SoftDeleteable\SoftDeleteableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [setAnnotationReader, [@annotation_reader]]

parameters:
  translation.locales: [es, en]
  directory.root: %kernel.root_dir%
  directory.images: %kernel.root_dir%/../web/uploads/images/
  swiftmailer.from: juanluis@company.mail

# Twig Configuration
twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
  debug: "%kernel.debug%"
  use_controller: false
  bundles: []
  #java: /usr/bin/java
  filters:
    cssrewrite: ~
    #closure:
    #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
    #yui_css:
    #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
  dbal:
    driver: "%database_driver%"
    host: "%database_host%"
    port: "%database_port%"
    dbname: "%database_name%"
    user: "%database_user%"
    password: "%database_password%"
    charset: UTF8
    # if using pdo_sqlite as your database driver, add the path in parameters.yml
    # e.g. database_path: "%kernel.root_dir%/data/data.db3"
    # path:     "%database_path%"

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    auto_mapping: true
    dql:
      string_functions:
        DAY: GruponivCPH\ServiceBundle\DQL\DayFunction
        MONTH: GruponivCPH\ServiceBundle\DQL\MonthFunction
        YEAR: GruponivCPH\ServiceBundle\DQL\YearFunction
    # mappings:
    #     gedmo_translatable:
    #         type: annotation
    #         alias: Gedmo
    #         prefix: Gedmo\Translatable\Entity
    #         # make sure vendor library location is correct
    #         dir: "%kernel.root_dir%/../src/Gedmo/Translatable/Entity"
    #     gedmo_translator:
    #         type: annotation
    #         prefix: Gedmo\Translator\Entity
    #         dir: "%kernel.root_dir%/../src/Gedmo/Translator/Entity"
    #         alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
    #         is_bundle: false
    #     gedmo_loggable:
    #         type: annotation
    #         alias: Gedmo
    #         prefix: Gedmo\Loggable\Entity
    #         dir: "%kernel.root_dir%/../src/Gedmo/Loggable/Entity"
    #     gedmo_tree:
    #         type: annotation
    #         alias: Gedmo
    #         prefix: Gedmo\Tree\Entity
    #         dir: "%kernel.root_dir%/../src/Gedmo/Tree/Entity"
    filters:
      softdeleteable:
        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
        enabled: true

# a2lix_translation_form:
#     locales: [es, en]                   # [Optionnal] Array of translations locales. Can be specified in the form.
#     default_required: false             # [Optionnal] Default to false. In this case, translation fields are not mark as required with html5
#     manager_registry: doctrine
#     templating: "A2lixTranslationFormBundle::default.html.twig"

# Swiftmailer Configuration
swiftmailer:
  transport: smtp
  host: 127.0.0.1
  username: juanluis@company.mail
  password: Cualqui3rc0sa
  spool: { type: memory }

#FOSUserBundle Configuration
fos_user:
  db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
  firewall_name: main
  user_class: GruponivCPH\UserBundle\Entity\User

  from_email:
    address: juanluis@company.mail
    sender_name: Lucia Zalbidea
# knp_paginator:
#   page_range: 10 # default page range used in pagination control
#   default_options:
#     page_name: page # page query parameter name
#     sort_field_name: sort # sort field query parameter name
#     sort_direction_name: direction # sort direction query parameter name
#     distinct: true # ensure distinct results, useful when ORM queries are using GROUP BY statements
#   template:
#     pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig # sliding pagination controls template
#     sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

# innocead_captcha:
#   width: 150
#   height: 30
#   max_chars: 4
#   min_chars: 4
#   char_max_size: 16
#   char_min_size: 16
#   char_transparent: 10
#   char_px_spacing: 30
#   char_random_color_lvl: 2 # (1 - very dark, 2 - dark, 3 - bright, 4 - very bright)
#   char_max_rot_angle: 30
#   effect_greyscale: false
#   effect_blur: false
#   noise_min_px: 0
#   noise_max_px: 0
#   noise_min_lines: 3
#   noise_max_lines: 3
#   noise_min_circles: 2
#   noise_max_circles: 2
#   noise_on_top: false
#   noise_color: 3 # (1 - color of the writing, 2 - color of the background, 3 - random color)
#   brush_size: 1 # brush noise size
#   bg_transparent: true # transparent background
#   bg_red: 238 # used if background is not transparen
#   bg_green: 255
#   bg_blue: 255
#   bg_border: false
#   flood_timer: 0 # min difference between last request and current request
#   max_refresh: 1000 # refreshes before user enter a valid code or expare session
#   test_queries_flood: false # test for request refreshes and flood timer
#   chars_used: "ABCDEFGHKLMNPRTWXYZ234569"
#   char_fonts: # array of used fonts (can be luggerbu.ttf, elephant.ttf, scrawl.ttf, alanden.ttf)
#     - luggerbu.ttf
