# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

# innocead_captcha:
#     class: Innocead\CaptchaBundle\Captcha
#     arguments: [ "@session" , "%innocead_captcha.config%"]
# innocead_captcha.form.type:
#     class: Innocead\CaptchaBundle\Form\Type\CaptchaType
#     arguments: ["%innocead_captcha.config%"]
#     tags:
#         - { name: form.type, alias: innocead_captcha }
# innocead_captcha.validator:
#     class: Innocead\CaptchaBundle\Validator\Constraints\CaptchaValidator
#     arguments: ["@innocead_captcha"]
#     tags:
#         - { name: validator.constraint_validator, alias: innocead_captcha.validator }
