answerticket:
    path:     /
    defaults: { _controller: "ServiceBundle:AnswerTicket:index" }

answerticket_show:
    path:     /{id}/show
    defaults: { _controller: "ServiceBundle:AnswerTicket:show" }

answerticket_new:
    path:     /new
    defaults: { _controller: "ServiceBundle:AnswerTicket:new" }

answerticket_create:
    path:     /create
    defaults: { _controller: "ServiceBundle:AnswerTicket:create" }
    methods:  POST

answerticket_edit:
    path:     /{id}/edit
    defaults: { _controller: "ServiceBundle:AnswerTicket:edit" }

answerticket_update:
    path:     /{id}/update
    defaults: { _controller: "ServiceBundle:AnswerTicket:update" }
    methods:  [POST, PUT]

answerticket_delete:
    path:     /{id}/delete
    defaults: { _controller: "ServiceBundle:AnswerTicket:delete" }
    methods:  [POST, DELETE]
