emailsender:
    path:     /
    defaults: { _controller: "ServiceBundle:EmailSender:index" }

emailsender_show:
    path:     /{id}/show
    defaults: { _controller: "ServiceBundle:EmailSender:show" }

emailsender_new:
    path:     /new
    defaults: { _controller: "ServiceBundle:EmailSender:new" }

emailsender_create:
    path:     /create
    defaults: { _controller: "ServiceBundle:EmailSender:create" }
    methods:  POST

emailsender_edit:
    path:     /{id}/edit
    defaults: { _controller: "ServiceBundle:EmailSender:edit" }

emailsender_update:
    path:     /{id}/update
    defaults: { _controller: "ServiceBundle:EmailSender:update" }
    methods:  [POST, PUT]

emailsender_delete:
    path:     /{id}/delete
    defaults: { _controller: "ServiceBundle:EmailSender:delete" }
    methods:  [POST, DELETE]
