freeshippingcountry:
    path:     /
    defaults: { _controller: "ServiceBundle:CountrySend:index" }

freeshippingcountry_show:
    path:     /{id}/show
    defaults: { _controller: "ServiceBundle:CountrySend:show" }

freeshippingcountry_new:
    path:     /new
    defaults: { _controller: "ServiceBundle:CountrySend:new" }

freeshippingcountry_create:
    path:     /create
    defaults: { _controller: "ServiceBundle:CountrySend:create" }
    methods:  POST

freeshippingcountry_edit:
    path:     /{id}/edit
    defaults: { _controller: "ServiceBundle:CountrySend:edit" }

freeshippingcountry_update:
    path:     /{id}/update
    defaults: { _controller: "ServiceBundle:CountrySend:update" }
    methods:  [POST, PUT]

freeshippingcountry_delete:
    path:     /{id}/delete
    defaults: { _controller: "ServiceBundle:CountrySend:delete" }
    methods:  [POST, DELETE]
