<?php

namespace GruponivCPH\ServiceBundle\Repository;

/**
 * ProductImageEffectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function clientsBetweenDates($startDate, $endDate)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT c FROM ServiceBundle:Client c WHERE c.creationDate >= :startDate AND"
                . " c.creationDate <= :endDate");
        
        $consulta->setParameter("startDate", $startDate);
        $consulta->setParameter("endDate", $endDate);
                
        return $consulta->getResult();
    }       
}
