<?php

namespace GruponivCPH\ServiceBundle\Repository;

/**
 * ProductImageEffectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeRepository extends \Doctrine\ORM\EntityRepository
{
    public function noticesOrdered()
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT d
                FROM ServiceBundle:Notice d ORDER BY d.date ASC");
                
        return $consulta->getResult();
    }
    
    public function noticesCategoryOrdered($category)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT d
                FROM ServiceBundle:Notice d JOIN d.category c WHERE c = :category ORDER BY d.date ASC");
        
        $query->setParameter("category", $category);
        
        return $query->getResult();
    }
    

}
