<?php

namespace GruponivCPH\ServiceBundle\Repository;

/**
 * ProductImageEffectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBetweenDates($startDate, $endDate)
    {
        $em = $this->getEntityManager();
        $sql = "SELECT o FROM ServiceBundle:OrderClient o WHERE o.creationDate >= :startDate AND"
                . " o.creationDate <= :endDate AND o.status = 'Entregado'";
        $query = $em->createQuery($sql);
        
        $query->setParameter("startDate", $startDate);
        $query->setParameter("endDate", $endDate);
        
        return $query->getResult();
    }
    
    
    public function orderClient($client)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT o FROM ServiceBundle:OrderClient o WHERE o.client = :client ORDER BY o.creationDate DESC");
        
        $consulta->setParameter("client", $client);
                
        return $consulta->getResult();
    }
    
    public function orders()
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT o FROM ServiceBundle:OrderClient o ORDER BY o.creationDate DESC");
                       
        return $consulta->getResult();
    }
}
