<?php

namespace GruponivCPH\ServiceBundle\Repository;

/**
 * ProductImageEffectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function productsSearch($term)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT d
                FROM ServiceBundle:Product d  WHERE d.name LIKE :term");

        $consulta->setParameter("term", "%" . $term . "%");
                
        return $consulta->getResult();
    }
    
    
    public function productsByCategory($category)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT d
                FROM ServiceBundle:Product d JOIN d.categories c WHERE c = :category");

        $consulta->setParameter("category", $category);
                
        return $consulta->getResult();
    }
    

}
