<?php

namespace GruponivCPH\ServiceBundle\Repository;

/**
 * ProductImageEffectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function productImagesOrdered($product)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT d
                FROM ServiceBundle:ProductImage d JOIN d.product p WHERE p = :product ORDER BY d.image ASC");

        $consulta->setParameter("product", $product);
                
        return $consulta->getResult();
    }
    

}
