<?php

namespace GruponivCPH\ServiceBundle\Repository;

/**
 * QuestionTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionTicketRepository extends \Doctrine\ORM\EntityRepository
{   
    public function allQuestionOrderByTicket($ticket)
    {
        $em = $this->getEntityManager();
        $sql = "SELECT q FROM ServiceBundle:QuestionTicket q JOIN q.ticket t WHERE t = :ticket ORDER BY  q.creationDate ASC";
        
        $query = $em->createQuery($sql);
        $query->setParameter("ticket", $ticket);
        
        return $query->getResult();
    }
    
    
    public function allQuestionOrderByTicketDesc($ticket)
    {
        $em = $this->getEntityManager();
        $sql = "SELECT q FROM ServiceBundle:QuestionTicket q JOIN q.ticket t WHERE t = :ticket ORDER BY  q.creationDate DESC";
        
        $query = $em->createQuery($sql);
        $query->setParameter("ticket", $ticket);
        
        return $query->getResult();
    }
    
    public function allQuestionOrder($client)
    {
        $em = $this->getEntityManager();
        $sql = "SELECT q FROM ServiceBundle:QuestionTicket q JOIN q.ticket t WHERE t.client = :client ORDER BY q.creationDate DESC";
        
        $query = $em->createQuery($sql);
        $query->setParameter("client", $client);
        
        return $query->getResult();
    }    
}
