<?php

namespace GruponivCPH\ServiceBundle\Repository;

/**
 * ProductImageEffectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends \Doctrine\ORM\EntityRepository
{
    public function stocksByCategory($category)
    {
        $em = $this->getEntityManager();
        $sql = "SELECT s FROM ServiceBundle:Stock s JOIN s.product p JOIN p.categories c"
                . " WHERE c = :category";
        
        $consulta = $em->createQuery($sql);
        
        $consulta->setParameter('category', $category);
        
        return $consulta->getResult();
    }
}
